name: Call Terraform Apply (Matrix)

on:
  workflow_dispatch:

jobs:
  call-apply:
    name: Call apply for ${{ matrix.env }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: dev01
            apply_status: fail
          - env: dev02
            apply_status: success
    uses: ./.github/workflows/terraform-apply-called.yml
    with:
      apply_status: ${{ matrix.apply_status }}
