name: Manual Sync Develop to Dev Branches

on:
  schedule:
    - cron: '*/5 * * * *' # Chạy mỗi 5 phút như bạn yêu cầu ở bước trước
  workflow_dispatch: # Giữ lại để chạy thủ công khi cần

jobs:
  force-push:
    name: Push to ${{ matrix.target_branch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_branch: ['deploy/dev01', 'deploy/dev02']
      fail-fast: false

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          # SỬ DỤNG PAT TẠI ĐÂY
          token: ${{ secrets.PAT }} 
          fetch-depth: 0
          ref: develop

      - name: Force Push to Target Branch
        run: |
          echo "Đang thực hiện force push từ develop sang ${{ matrix.target_branch }} bằng PAT..."
          # Đã checkout ref: develop nên local branch là develop. 
          # Ta dùng lệnh push trực tiếp từ local branch lên remote branch đích.
          git push origin develop:${{ matrix.target_branch }} --force