name: Manual Sync Develop to Dev Branches

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  force-push:
    name: Push to ${{ matrix.target_branch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_branch: ['deploy/dev01', 'deploy/dev02']
      fail-fast: false

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Force Push to Target Branch
        run: |
          echo "Đang thực hiện force push sang ${{ matrix.target_branch }}..."
          # Đảm bảo remote URL đã bao gồm Token để tránh hỏi username/pass
          # Checkout đã làm việc này thông qua persist-credentials: true
          git push origin develop:${{ matrix.target_branch }} --force