name: Terraform Apply (Weekly - Friday 5AM VN)

on:
  schedule:
    # 22:00 UTC Thứ 5 = 05:00 sáng Thứ 6 (UTC+7)
    - cron: "0 22 * * 4"
  workflow_dispatch:

    workflow_call:
    inputs:
      apply_status:
        description: "Status from terraform apply step"
        required: true
        type: string

jobs:
  terraform-apply:
    name: Terraform Apply (Mock)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: core

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Terraform Init
        run: terraform init -input=false

      # STEP APPLY (MOCK) – có OUTPUT
      - name: Terraform Apply (Mock)
        id: apply
        run: |
          echo "Running terraform apply (mock)..."
          APPLY_TIME= $(date -u)
          APPLY_STATUS= ${{ inputs.apply_status }}

          echo "apply_time=$APPLY_TIME" >> $GITHUB_OUTPUT
          echo "apply_status=$APPLY_STATUS" >> $GITHUB_OUTPUT

      # STEP REQUIRE – dùng output của step apply
      - name: Requir
        run: |
          echo "=== REQUIRE STEP ==="
          echo "Apply status : ${{ steps.apply.outputs.apply_status }}"
          echo "Apply time   : ${{ steps.apply.outputs.apply_time }}"

          if [ "${{ steps.apply.outputs.apply_status }}" != "success" ]; then
            echo "Apply failed, stop pipeline"
            exit 1
          fi

          echo "Apply OK, continue next actions..."
