name: Terraform Apply (Simple)

on:
  workflow_call:
    inputs:
      apply_status:
        required: true
        type: string

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      # STEP 1: dùng input, tạo output
      - name: Step 1 - Use input & set output
        id: step1
        run: |
          echo "Input status: ${{ inputs.apply_status }}"

          echo "result_status=${{ inputs.apply_status }}" >> $GITHUB_OUTPUT

      # STEP 2: dùng output của step 1
      - name: Step 2 - Consume output
        run: |
          echo "Output from step 1: ${{ steps.step1.outputs.result_status }}"

          if [ "${{ steps.step1.outputs.result_status }}" != "success" ]; then
            echo "❌ Status not success, fail workflow"
            exit 1
          fi

          echo "✅ Status success, continue"
