name: CD - Workflow Datadog Demo

on:
  workflow_dispatch:
    inputs:
      TF_DEMO_FAIL:
        description: "Set true to simulate failure"
        required: true
        default: "false"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_DEMO_FAIL: ${{ github.event.inputs.TF_DEMO_FAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Demo)
        run: |
          echo "Running terraform plan..."
          
          if [ "$TF_DEMO_FAIL" = "true" ]; then
            echo "Simulating terraform plan failure"
            exit 1
          fi
          
          echo "Terraform plan success"

      - name: Terraform Apply (Demo)
        if: success()
        run: |
          echo "Running terraform apply..."

          if [ "$TF_DEMO_FAIL" = "true" ]; then
            echo "Simulating terraform apply failure"
            exit 1
          fi

          echo "Terraform apply success"

      - name: Notify Failure
        if: failure()
        run: |
          echo "Workflow failed - you can push custom metric here"
