name: Maintain Resume Workflow

on:
  workflow_dispatch:
    inputs:
      SET_ENV:
        description: "Set environment (dev or prod)"
        required: false
        default: "dev"
      FAIL_SERVICE:
        description: "Force service failure"
        required: false
        default: "false"
      FAIL_CLOUDFRONT:
        description: "Force cloudfront failure"
        required: false
        default: "false"
      FAIL_SYNTHETIC:
        description: "Force synthetic test failure"
        required: false
        default: "false"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      env_id: ${{ steps.setvars.outputs.env_id }}
      runs_on: ${{ steps.setvars.outputs.runs_on }}

    steps:
      - name: Detect Environment
        id: setvars
        run: |
          echo "Force prepare failure"

          if [[ "${{ github.event.inputs.SET_ENV }}" == "prod" ]]; then
            ENV_ID="prod"
          else
            ENV_ID="dev"
          fi

          echo "env_id=${ENV_ID}" >> $GITHUB_OUTPUT
          echo "runs_on=ubuntu-latest" >> $GITHUB_OUTPUT

  service_apply:
    runs-on: ${{ needs.prepare.outputs.runs_on }}
    needs: prepare

    steps:
      - name: Service Apply
        run: |
          echo "Running service apply..."

          if [ "${{ github.event.inputs.FAIL_SERVICE }}" = "true" ]; then
            exit 1
          fi

          exit 0

  slack_notice_approval:
    runs-on: ${{ needs.prepare.outputs.runs_on }}
    needs: [prepare,service_apply]

    steps:
      - name: Send Slack Approval Notice
        run: |
          echo "Sending Slack approval notice..."

  approval:
    runs-on: ${{ needs.prepare.outputs.runs_on }}
    needs: [prepare, service_apply, slack_notice_approval]

    steps:
      - name: Waiting for approval
        run: echo "Approved"

  cloudfront_apply:
    runs-on: ${{ needs.prepare.outputs.runs_on }}
    needs: [prepare,approval]

    steps:
      - name: CloudFront Apply
        run: |
          echo "Running cloudfront apply..."

          if [ "${{ github.event.inputs.FAIL_CLOUDFRONT }}" = "true" ]; then
            exit 1
          fi

          exit 0

  synthetic_test:
    runs-on: ${{ needs.prepare.outputs.runs_on }}
    needs: 
      - prepare
      - service_apply
      - cloudfront_apply
    if: ${{ needs.service_apply.result == 'success' && needs.cloudfront_apply.result == 'success' }}

    steps:
      - name: Synthetic Test (Demo)
        run: |
          echo "Running synthetic test..."

          if [ "${{ github.event.inputs.FAIL_SYNTHETIC }}" = "true" ]; then
            exit 1
          fi
          exit 0
  
  notify_resume_result:
    runs-on: ${{ needs.prepare.outputs.runs_on }}
    needs:
      - prepare
      - service_apply
      - cloudfront_apply
      - synthetic_test
    if: ${{ always() && (needs.service_apply.result == 'failure' || needs.cloudfront_apply.result == 'failure' || needs.synthetic_test.result == 'failure') }}

    steps:
      - name: Push Terraform Failure Metric
        run: |
          TS=$(date +%s)

          JOB_FAILURE="apply"
          if [ "${SYNTHTIC_TEST_RESULT}" == "failure" ]; then
            JOB_FAILURE="synthetic-test"
          fi

          curl -X POST "https://api.datadoghq.com/api/v2/series" \
          -H "Content-Type: application/json" \
          -H "DD-API-KEY: ${DD_API_KEY}" \
          -d @- <<EOF
          {
            "series": [
              {
                "metric": "test.execute.failure",
                "type": 1,
                "points": [
                  {
                    "timestamp": ${TS},
                    "value": 1
                  }
                ],
                "tags": [
                  "env:${ENV_ID}",
                  "status:failure",
                  "part:resume",
                  "job:${JOB_FAILURE}"
                ]
              }
            ]
          }
          EOF
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          ENV_ID: ${{ needs.prepare.outputs.env_id }}
          SYNTHTIC_TEST_RESULT: ${{ needs.synthetic_test.result }}

  slack_message_creation:
    runs-on: ${{ needs.prepare.outputs.runs_on }}
    needs:
      - prepare
      - service_apply
      - cloudfront_apply

    if: always()

    steps:
      - name: Send Final Slack Message
        run: |
          echo "Sending final Slack summary..."
